# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["TicketSystem.API/TicketSystem.API.csproj", "TicketSystem.API/"]
COPY ["TicketSystem.Infrastructure/TicketSystem.Infrastructure.csproj", "TicketSystem.Infrastructure/"]
COPY ["TicketSystem.Application/TicketSystem.Application.csproj", "TicketSystem.Application/"]
COPY ["TicketSystem.Domain/TicketSystem.Domain.csproj", "TicketSystem.Domain/"]
COPY ["TicketSystem.Core/TicketSystem.Core.csproj", "TicketSystem.Core/"]
COPY ["TicketSystem.Infrastructure.Database/TicketSystem.Infrastructure.Database.csproj", "TicketSystem.Infrastructure.Database/"]
COPY ["TicketSystem.ServiceDefaults/TicketSystem.ServiceDefaults.csproj", "TicketSystem.ServiceDefaults/"]
RUN dotnet restore "./TicketSystem.API/TicketSystem.API.csproj"
COPY . .
WORKDIR "/src/TicketSystem.API"
RUN dotnet build "./TicketSystem.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TicketSystem.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TicketSystem.API.dll"]